return {
	auto_rally_interval = 1,
	ban_first = false,
	hero_scan_interval = 5,
	high_threat_candidate_limit = 2,
	home_guard_nodes = 65,
	home_urgent_nodes_melee = 70,
	home_urgent_nodes_ranged = 20,
	in_danger_hp = 0.2,
	key_label_map = {
		auto_rally_interval = "Khoảng thời gian tự tập kết",
		ban_first = "Không tự tập kết anh hùng ở ô đầu",
		hero_scan_interval = "Khoảng thời gian quét anh hùng",
		home_guard_nodes = "Số nút di chuyển về chặn khẩn cấp của anh hùng tầm xa",
		home_urgent_nodes_melee = "Số nút di chuyển về khẩn cấp của anh hùng cận chiến",
		home_urgent_nodes_ranged = "Số nút chặn tại chỗ của anh hùng tầm xa",
		in_danger_hp = "Ngưỡng máu rút lui",
		manual_pause_seconds = "Thời gian giữ yên",
		melee_skill_cooldown_min = "Ngưỡng đánh giá kỹ năng cận chiến",
		ranged_fast_cooldown = "Ngưỡng đánh giá đòn đánh tầm xa",
		ranged_skill_cooldown_min = "Ngưỡng đánh giá kỹ năng tầm xa",
		resume_hp = "Ngưỡng máu trở lại tấn công",
		safe_distance = "Khoảng cách an toàn",
		target_candidate_limit = "Giới hạn số mục tiêu kiểm tra",
		timed_skill_cooldown_min = "Ngưỡng đánh giá kỹ năng định kỳ",
	},
	key_order_list = {
		"ban_first",
		"in_danger_hp",
		"safe_distance",
		"resume_hp",
		"auto_rally_interval",
		"hero_scan_interval",
		"home_guard_nodes",
		"home_urgent_nodes_melee",
		"home_urgent_nodes_ranged",
		"manual_pause_seconds",
		"melee_skill_cooldown_min",
		"ranged_fast_cooldown",
		"ranged_skill_cooldown_min",
		"timed_skill_cooldown_min",
		"target_candidate_limit",
	},
	manual_pause_seconds = 8,
	melee_skill_cooldown_min = 4,
	ranged_fast_cooldown = 4,
	ranged_skill_cooldown_min = 4,
	resume_hp = 0.7,
	safe_distance = 100,
	target_candidate_limit = 4,
	timed_skill_cooldown_min = 3,
}
