return {
	auto_rally_interval = 1,
	ban_first = false,
	hero_scan_interval = 5,
	high_threat_candidate_limit = 2,
	home_guard_nodes = 65,
	home_urgent_nodes_melee = 70,
	home_urgent_nodes_ranged = 20,
	in_danger_hp = 0.2,
	key_label_map = {
		auto_rally_interval = "自动调集间隔",
		ban_first = "一号位英雄不自动调集",
		hero_scan_interval = "英雄扫描间隔",
		home_guard_nodes = "远程紧急回家阻拦节点数",
		home_urgent_nodes_melee = "近战紧急回家节点数",
		home_urgent_nodes_ranged = "远程拦截不走位节点数",
		in_danger_hp = "后撤生命阈值",
		manual_pause_seconds = "静默时间",
		melee_skill_cooldown_min = "近战技能判断阈值",
		ranged_fast_cooldown = "远程普攻判断阈值",
		ranged_skill_cooldown_min = "远程技能判断阈值",
		resume_hp = "恢复进攻生命阈值",
		safe_distance = "安全距离",
		target_candidate_limit = "索敌检验数量上限",
		timed_skill_cooldown_min = "定时技能判断阈值",
	},
	key_order_list = {
		"ban_first",
		"in_danger_hp",
		"safe_distance",
		"resume_hp",
		"auto_rally_interval",
		"hero_scan_interval",
		"home_guard_nodes",
		"home_urgent_nodes_melee",
		"home_urgent_nodes_ranged",
		"manual_pause_seconds",
		"melee_skill_cooldown_min",
		"ranged_fast_cooldown",
		"ranged_skill_cooldown_min",
		"timed_skill_cooldown_min",
		"target_candidate_limit",
	},
	manual_pause_seconds = 8,
	melee_skill_cooldown_min = 4,
	ranged_fast_cooldown = 4,
	ranged_skill_cooldown_min = 4,
	resume_hp = 0.7,
	safe_distance = 100,
	target_candidate_limit = 4,
	timed_skill_cooldown_min = 3,
}
