return {
	hero_gerald_g6 = {
		display_key = "HERO_GERALD_G6",
		description_key = "HERO_GERALD_G6_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_GERALD_G6_SKILL_A_1_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_A_1_DESCRIPTION",
				icon = "hero_gerald_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_GERALD_G6_SKILL_A_2_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_A_2_DESCRIPTION",
				icon = "hero_gerald_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_GERALD_G6_SKILL_A_3_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_A_3_DESCRIPTION",
				icon = "hero_gerald_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_GERALD_G6_SKILL_B_1_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_B_1_DESCRIPTION",
				icon = "hero_gerald_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_GERALD_G6_SKILL_B_2_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_B_2_DESCRIPTION",
				icon = "hero_gerald_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_GERALD_G6_SKILL_B_3_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_B_3_DESCRIPTION",
				icon = "hero_gerald_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_GERALD_G6_SKILL_C_1_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_C_1_DESCRIPTION",
				icon = "hero_gerald_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_GERALD_G6_SKILL_C_2_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_C_2_DESCRIPTION",
				icon = "hero_gerald_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_GERALD_G6_SKILL_C_3_TITLE",
				description_key = "HERO_GERALD_G6_SKILL_C_3_DESCRIPTION",
				icon = "hero_gerald_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_GERALD_G6_TALENT_1_TITLE",
				description_key = "HERO_GERALD_G6_TALENT_1_DESCRIPTION",
				icon = "hero_gerald_skill_icon_05",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_GERALD_G6_TALENT_2_TITLE",
				description_key = "HERO_GERALD_G6_TALENT_2_DESCRIPTION",
				icon = "hero_gerald_skill_icon_06",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_GERALD_G6_ULT_TITLE",
				description_key = "HERO_GERALD_G6_ULT_DESCRIPTION",
				icon = "hero_gerald_skill_icon_04",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_XP_GAIN_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_XP_GAIN_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_buff_dur",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_FASTER_RESPAWN_TIME_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_FASTER_RESPAWN_TIME_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_armor",
				x = 785,
				y = 300,
			},
		},
	},
	hero_zefira = {
		display_key = "HERO_ZEFIRA",
		description_key = "HERO_ZEFIRA_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_ZEFIRA_SKILL_A_1_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_A_1_DESCRIPTION",
				icon = "hero_zefira_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_ZEFIRA_SKILL_A_2_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_A_2_DESCRIPTION",
				icon = "hero_zefira_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_ZEFIRA_SKILL_A_3_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_A_3_DESCRIPTION",
				icon = "hero_zefira_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_ZEFIRA_SKILL_B_1_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_B_1_DESCRIPTION",
				icon = "hero_zefira_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_ZEFIRA_SKILL_B_2_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_B_2_DESCRIPTION",
				icon = "hero_zefira_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_ZEFIRA_SKILL_B_3_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_B_3_DESCRIPTION",
				icon = "hero_zefira_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_ZEFIRA_SKILL_C_1_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_C_1_DESCRIPTION",
				icon = "hero_zefira_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_ZEFIRA_SKILL_C_2_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_C_2_DESCRIPTION",
				icon = "hero_zefira_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_ZEFIRA_SKILL_C_3_TITLE",
				description_key = "HERO_ZEFIRA_SKILL_C_3_DESCRIPTION",
				icon = "hero_zefira_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_ZEFIRA_TALENT_1_TITLE",
				description_key = "HERO_ZEFIRA_TALENT_1_DESCRIPTION",
				icon = "hero_zefira_skill_icon_05",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_ZEFIRA_TALENT_2_TITLE",
				description_key = "HERO_ZEFIRA_TALENT_2_DESCRIPTION",
				icon = "hero_zefira_skill_icon_06",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_ZEFIRA_ULT_TITLE",
				description_key = "HERO_ZEFIRA_ULT_DESCRIPTION",
				icon = "hero_zefira_skill_icon_04",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_FASTER_RESPAWN_TIME_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_FASTER_RESPAWN_TIME_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_regen",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 785,
				y = 300,
			},
		},
	},
	hero_bolin_g6 = {
		display_key = "HERO_BOLIN_G6",
		description_key = "HERO_BOLIN_G6_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_BOLIN_G6_SKILL_A_1_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_A_1_DESCRIPTION",
				icon = "hero_bolin_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_BOLIN_G6_SKILL_A_2_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_A_2_DESCRIPTION",
				icon = "hero_bolin_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_BOLIN_G6_SKILL_A_3_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_A_3_DESCRIPTION",
				icon = "hero_bolin_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_BOLIN_G6_SKILL_B_1_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_B_1_DESCRIPTION",
				icon = "hero_bolin_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_BOLIN_G6_SKILL_B_2_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_B_2_DESCRIPTION",
				icon = "hero_bolin_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_BOLIN_G6_SKILL_B_3_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_B_3_DESCRIPTION",
				icon = "hero_bolin_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_BOLIN_G6_SKILL_C_1_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_C_1_DESCRIPTION",
				icon = "hero_bolin_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_BOLIN_G6_SKILL_C_2_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_C_2_DESCRIPTION",
				icon = "hero_bolin_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_BOLIN_G6_SKILL_C_3_TITLE",
				description_key = "HERO_BOLIN_G6_SKILL_C_3_DESCRIPTION",
				icon = "hero_bolin_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_BOLIN_G6_TALENT_1_TITLE",
				description_key = "HERO_BOLIN_G6_TALENT_1_DESCRIPTION",
				icon = "hero_bolin_skill_icon_05",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_BOLIN_G6_TALENT_2_TITLE",
				description_key = "HERO_BOLIN_G6_TALENT_2_DESCRIPTION",
				icon = "hero_bolin_skill_icon_06",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_BOLIN_G6_ULT_TITLE",
				description_key = "HERO_BOLIN_G6_ULT_DESCRIPTION",
				icon = "hero_bolin_skill_icon_04",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_ROF_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ROF_INCREASE_DESCRIPTION",
				icon = "icons_passive_attack_speed",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_RANGE_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_RANGE_INCREASE_DESCRIPTION",
				icon = "icons_passive_range",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_armor",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 785,
				y = 300,
			},
		},
	},
	hero_malik_g6 = {
		display_key = "HERO_MALIK_G6",
		description_key = "HERO_MALIK_G6_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_MALIK_G6_SKILL_A_1_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_A_1_DESCRIPTION",
				icon = "hero_malik_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_MALIK_G6_SKILL_A_2_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_A_2_DESCRIPTION",
				icon = "hero_malik_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_MALIK_G6_SKILL_A_3_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_A_3_DESCRIPTION",
				icon = "hero_malik_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_MALIK_G6_SKILL_B_1_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_B_1_DESCRIPTION",
				icon = "hero_malik_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_MALIK_G6_SKILL_B_2_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_B_2_DESCRIPTION",
				icon = "hero_malik_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_MALIK_G6_SKILL_B_3_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_B_3_DESCRIPTION",
				icon = "hero_malik_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_MALIK_G6_SKILL_C_1_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_C_1_DESCRIPTION",
				icon = "hero_malik_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_MALIK_G6_SKILL_C_2_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_C_2_DESCRIPTION",
				icon = "hero_malik_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_MALIK_G6_SKILL_C_3_TITLE",
				description_key = "HERO_MALIK_G6_SKILL_C_3_DESCRIPTION",
				icon = "hero_malik_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_MALIK_G6_TALENT_1_TITLE",
				description_key = "HERO_MALIK_G6_TALENT_1_DESCRIPTION",
				icon = "hero_malik_skill_icon_05",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_MALIK_G6_TALENT_2_TITLE",
				description_key = "HERO_MALIK_G6_TALENT_2_DESCRIPTION",
				icon = "hero_malik_skill_icon_06",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_MALIK_G6_ULT_TITLE",
				description_key = "HERO_MALIK_G6_ULT_DESCRIPTION",
				icon = "hero_malik_skill_icon_04",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_regen",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_MOV_SPEED_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_MOV_SPEED_INCREASE_DESCRIPTION",
				icon = "icons_passive_slow",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_DMG_COND_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_DMG_COND_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_REVIVE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_REVIVE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 785,
				y = 300,
			},
		},
	},
	hero_ashbite = {
		display_key = "HERO_ASHBITE",
		description_key = "HERO_ASHBITE_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_ASHBITE_SKILL_A_1_TITLE",
				description_key = "HERO_ASHBITE_SKILL_A_1_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_ASHBITE_SKILL_A_2_TITLE",
				description_key = "HERO_ASHBITE_SKILL_A_2_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_ASHBITE_SKILL_A_3_TITLE",
				description_key = "HERO_ASHBITE_SKILL_A_3_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_ASHBITE_SKILL_B_1_TITLE",
				description_key = "HERO_ASHBITE_SKILL_B_1_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_ASHBITE_SKILL_B_2_TITLE",
				description_key = "HERO_ASHBITE_SKILL_B_2_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_ASHBITE_SKILL_B_3_TITLE",
				description_key = "HERO_ASHBITE_SKILL_B_3_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_ASHBITE_SKILL_C_1_TITLE",
				description_key = "HERO_ASHBITE_SKILL_C_1_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_ASHBITE_SKILL_C_2_TITLE",
				description_key = "HERO_ASHBITE_SKILL_C_2_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_ASHBITE_SKILL_C_3_TITLE",
				description_key = "HERO_ASHBITE_SKILL_C_3_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_ASHBITE_TALENT_1_TITLE",
				description_key = "HERO_ASHBITE_TALENT_1_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_05",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_ASHBITE_TALENT_2_TITLE",
				description_key = "HERO_ASHBITE_TALENT_2_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_06",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_ASHBITE_ULT_TITLE",
				description_key = "HERO_ASHBITE_ULT_DESCRIPTION",
				icon = "hero_ashbite_skill_icon_04",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_RANGE_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_RANGE_INCREASE_DESCRIPTION",
				icon = "icons_passive_range",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_regen",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 785,
				y = 300,
			},
		},
	},
	hero_rhodes = {
		display_key = "HERO_RHODES",
		description_key = "HERO_RHODES_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_RHODES_SKILL_A_1_TITLE",
				description_key = "HERO_RHODES_SKILL_A_1_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_RHODES_SKILL_A_2_TITLE",
				description_key = "HERO_RHODES_SKILL_A_2_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_RHODES_SKILL_A_3_TITLE",
				description_key = "HERO_RHODES_SKILL_A_3_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_RHODES_SKILL_B_1_TITLE",
				description_key = "HERO_RHODES_SKILL_B_1_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_RHODES_SKILL_B_2_TITLE",
				description_key = "HERO_RHODES_SKILL_B_2_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_RHODES_SKILL_B_3_TITLE",
				description_key = "HERO_RHODES_SKILL_B_3_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_RHODES_SKILL_C_1_TITLE",
				description_key = "HERO_RHODES_SKILL_C_1_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_RHODES_SKILL_C_2_TITLE",
				description_key = "HERO_RHODES_SKILL_C_2_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_RHODES_SKILL_C_3_TITLE",
				description_key = "HERO_RHODES_SKILL_C_3_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_RHODES_TALENT_1_TITLE",
				description_key = "HERO_RHODES_TALENT_1_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_05",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_RHODES_TALENT_2_TITLE",
				description_key = "HERO_RHODES_TALENT_2_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_06",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_RHODES_ULT_TITLE",
				description_key = "HERO_RHODES_ULT_DESCRIPTION",
				icon = "hero_rhodes_skill_icon_04",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_regen",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_armor",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 785,
				y = 300,
			},
		},
	},
	hero_drakkan = {
		display_key = "HERO_DRAKKAN",
		description_key = "HERO_DRAKKAN_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_DRAKKAN_SKILL_A_1_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_A_1_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_DRAKKAN_SKILL_A_2_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_A_2_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_DRAKKAN_SKILL_A_3_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_A_3_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_DRAKKAN_SKILL_B_1_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_B_1_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_DRAKKAN_SKILL_B_2_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_B_2_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_DRAKKAN_SKILL_B_3_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_B_3_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_DRAKKAN_SKILL_C_1_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_C_1_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_DRAKKAN_SKILL_C_2_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_C_2_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_DRAKKAN_SKILL_C_3_TITLE",
				description_key = "HERO_DRAKKAN_SKILL_C_3_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_DRAKKAN_TALENT_1_TITLE",
				description_key = "HERO_DRAKKAN_TALENT_1_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_05",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_DRAKKAN_TALENT_2_TITLE",
				description_key = "HERO_DRAKKAN_TALENT_2_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_06",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_DRAKKAN_ULT_TITLE",
				description_key = "HERO_DRAKKAN_ULT_DESCRIPTION",
				icon = "hero_drakkan_skill_icon_04",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_MR_RESISTANCE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_MR_RESISTANCE_DESCRIPTION",
				icon = "icons_passive_skill_armor",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_regen",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_BASE_AOE_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_AOE_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 785,
				y = 300,
			},
		},
	},
	hero_myriath = {
		display_key = "HERO_MYRIATH",
		description_key = "HERO_MYRIATH_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_MYRIATH_SKILL_A_1_TITLE",
				description_key = "HERO_MYRIATH_SKILL_A_1_DESCRIPTION",
				icon = "hero_myriath_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_MYRIATH_SKILL_A_2_TITLE",
				description_key = "HERO_MYRIATH_SKILL_A_2_DESCRIPTION",
				icon = "hero_myriath_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_MYRIATH_SKILL_A_3_TITLE",
				description_key = "HERO_MYRIATH_SKILL_A_3_DESCRIPTION",
				icon = "hero_myriath_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_MYRIATH_SKILL_B_1_TITLE",
				description_key = "HERO_MYRIATH_SKILL_B_1_DESCRIPTION",
				icon = "hero_myriath_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_MYRIATH_SKILL_B_2_TITLE",
				description_key = "HERO_MYRIATH_SKILL_B_2_DESCRIPTION",
				icon = "hero_myriath_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_MYRIATH_SKILL_B_3_TITLE",
				description_key = "HERO_MYRIATH_SKILL_B_3_DESCRIPTION",
				icon = "hero_myriath_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_MYRIATH_SKILL_C_1_TITLE",
				description_key = "HERO_MYRIATH_SKILL_C_1_DESCRIPTION",
				icon = "hero_myriath_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_MYRIATH_SKILL_C_2_TITLE",
				description_key = "HERO_MYRIATH_SKILL_C_2_DESCRIPTION",
				icon = "hero_myriath_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_MYRIATH_SKILL_C_3_TITLE",
				description_key = "HERO_MYRIATH_SKILL_C_3_DESCRIPTION",
				icon = "hero_myriath_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_MYRIATH_TALENT_1_TITLE",
				description_key = "HERO_MYRIATH_TALENT_1_DESCRIPTION",
				icon = "hero_myriath_skill_icon_04",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_MYRIATH_TALENT_2_TITLE",
				description_key = "HERO_MYRIATH_TALENT_2_DESCRIPTION",
				icon = "hero_myriath_skill_icon_05",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_MYRIATH_ULT_TITLE",
				description_key = "HERO_MYRIATH_ULT_DESCRIPTION",
				icon = "hero_myriath_skill_icon_06",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_MOV_SPEED_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_MOV_SPEED_INCREASE_DESCRIPTION",
				icon = "icons_passive_slow",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_ROF_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ROF_INCREASE_DESCRIPTION",
				icon = "icons_passive_attack_speed",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_DODGE_CHANCE_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_DODGE_CHANCE_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_block",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 785,
				y = 300,
			},
		},
	},
	hero_connor = {
		display_key = "HERO_CONNOR",
		description_key = "HERO_CONNOR_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_CONNOR_SKILL_A_1_TITLE",
				description_key = "HERO_CONNOR_SKILL_A_1_DESCRIPTION",
				icon = "hero_connor_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_CONNOR_SKILL_A_2_TITLE",
				description_key = "HERO_CONNOR_SKILL_A_2_DESCRIPTION",
				icon = "hero_connor_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_CONNOR_SKILL_A_3_TITLE",
				description_key = "HERO_CONNOR_SKILL_A_3_DESCRIPTION",
				icon = "hero_connor_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_CONNOR_SKILL_B_1_TITLE",
				description_key = "HERO_CONNOR_SKILL_B_1_DESCRIPTION",
				icon = "hero_connor_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_CONNOR_SKILL_B_2_TITLE",
				description_key = "HERO_CONNOR_SKILL_B_2_DESCRIPTION",
				icon = "hero_connor_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_CONNOR_SKILL_B_3_TITLE",
				description_key = "HERO_CONNOR_SKILL_B_3_DESCRIPTION",
				icon = "hero_connor_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_CONNOR_SKILL_C_1_TITLE",
				description_key = "HERO_CONNOR_SKILL_C_1_DESCRIPTION",
				icon = "hero_connor_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_CONNOR_SKILL_C_2_TITLE",
				description_key = "HERO_CONNOR_SKILL_C_2_DESCRIPTION",
				icon = "hero_connor_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_CONNOR_SKILL_C_3_TITLE",
				description_key = "HERO_CONNOR_SKILL_C_3_DESCRIPTION",
				icon = "hero_connor_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_CONNOR_TALENT_1_TITLE",
				description_key = "HERO_CONNOR_TALENT_1_DESCRIPTION",
				icon = "hero_connor_skill_icon_04",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_CONNOR_TALENT_2_TITLE",
				description_key = "HERO_CONNOR_TALENT_2_DESCRIPTION",
				icon = "hero_connor_skill_icon_05",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_CONNOR_ULT_TITLE",
				description_key = "HERO_CONNOR_ULT_DESCRIPTION",
				icon = "hero_connor_skill_icon_06",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_armor",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_ROF_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ROF_INCREASE_DESCRIPTION",
				icon = "icons_passive_attack_speed",
				x = 785,
				y = 300,
			},
		},
	},
	hero_ignus_g6 = {
		display_key = "HERO_IGNUS_G6",
		description_key = "HERO_IGNUS_G6_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_IGNUS_G6_SKILL_A_1_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_A_1_DESCRIPTION",
				icon = "hero_ignus_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_IGNUS_G6_SKILL_A_2_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_A_2_DESCRIPTION",
				icon = "hero_ignus_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_IGNUS_G6_SKILL_A_3_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_A_3_DESCRIPTION",
				icon = "hero_ignus_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_IGNUS_G6_SKILL_B_1_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_B_1_DESCRIPTION",
				icon = "hero_ignus_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_IGNUS_G6_SKILL_B_2_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_B_2_DESCRIPTION",
				icon = "hero_ignus_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_IGNUS_G6_SKILL_B_3_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_B_3_DESCRIPTION",
				icon = "hero_ignus_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_IGNUS_G6_SKILL_C_1_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_C_1_DESCRIPTION",
				icon = "hero_ignus_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_IGNUS_G6_SKILL_C_2_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_C_2_DESCRIPTION",
				icon = "hero_ignus_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_IGNUS_G6_SKILL_C_3_TITLE",
				description_key = "HERO_IGNUS_G6_SKILL_C_3_DESCRIPTION",
				icon = "hero_ignus_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_IGNUS_G6_TALENT_1_TITLE",
				description_key = "HERO_IGNUS_G6_TALENT_1_DESCRIPTION",
				icon = "hero_ignus_skill_icon_04",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_IGNUS_G6_TALENT_2_TITLE",
				description_key = "HERO_IGNUS_G6_TALENT_2_DESCRIPTION",
				icon = "hero_ignus_skill_icon_05",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_IGNUS_G6_ULT_TITLE",
				description_key = "HERO_IGNUS_G6_ULT_DESCRIPTION",
				icon = "hero_ignus_skill_icon_06",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_TAKE_FLIGHT_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_TAKE_FLIGHT_DESCRIPTION",
				icon = "icons_passive_slow",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HEALTH_REGEN_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_regen",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 785,
				y = 300,
			},
		},
	},
	hero_oni_g6 = {
		display_key = "HERO_ONI_G6",
		description_key = "HERO_ONI_G6_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_ONI_G6_SKILL_A_1_TITLE",
				description_key = "HERO_ONI_G6_SKILL_A_1_DESCRIPTION",
				icon = "hero_oni_skill_icon_02",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_ONI_G6_SKILL_A_2_TITLE",
				description_key = "HERO_ONI_G6_SKILL_A_2_DESCRIPTION",
				icon = "hero_oni_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_ONI_G6_SKILL_A_3_TITLE",
				description_key = "HERO_ONI_G6_SKILL_A_3_DESCRIPTION",
				icon = "hero_oni_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_ONI_G6_SKILL_B_1_TITLE",
				description_key = "HERO_ONI_G6_SKILL_B_1_DESCRIPTION",
				icon = "hero_oni_skill_icon_01",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_ONI_G6_SKILL_B_2_TITLE",
				description_key = "HERO_ONI_G6_SKILL_B_2_DESCRIPTION",
				icon = "hero_oni_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_ONI_G6_SKILL_B_3_TITLE",
				description_key = "HERO_ONI_G6_SKILL_B_3_DESCRIPTION",
				icon = "hero_oni_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_ONI_G6_SKILL_C_1_TITLE",
				description_key = "HERO_ONI_G6_SKILL_C_1_DESCRIPTION",
				icon = "hero_oni_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_ONI_G6_SKILL_C_2_TITLE",
				description_key = "HERO_ONI_G6_SKILL_C_2_DESCRIPTION",
				icon = "hero_oni_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_ONI_G6_SKILL_C_3_TITLE",
				description_key = "HERO_ONI_G6_SKILL_C_3_DESCRIPTION",
				icon = "hero_oni_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_ONI_G6_TALENT_1_TITLE",
				description_key = "HERO_ONI_G6_TALENT_1_DESCRIPTION",
				icon = "hero_oni_skill_icon_04",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_ONI_G6_TALENT_2_TITLE",
				description_key = "HERO_ONI_G6_TALENT_2_DESCRIPTION",
				icon = "hero_oni_skill_icon_05",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_ONI_G6_ULT_TITLE",
				description_key = "HERO_ONI_G6_ULT_DESCRIPTION",
				icon = "hero_oni_skill_icon_06",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ARMOR_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_armor",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_ROF_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_ROF_INCREASE_DESCRIPTION",
				icon = "icons_passive_attack_speed",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 785,
				y = 300,
			},
		},
	},
	hero_illiana = {
		display_key = "HERO_ILLIANA",
		description_key = "HERO_ILLIANA_DESC",
		nodes = {
			skill_a = {
				cost = 1,
				title_key = "HERO_ILLIANA_SKILL_A_1_TITLE",
				description_key = "HERO_ILLIANA_SKILL_A_1_DESCRIPTION",
				icon = "hero_illiana_skill_icon_01",
				x = 105,
				y = 115,
				tier = 1,
			},
			upg_sa1 = {
				cost = 2,
				title_key = "HERO_ILLIANA_SKILL_A_2_TITLE",
				description_key = "HERO_ILLIANA_SKILL_A_2_DESCRIPTION",
				icon = "hero_illiana_skill_icon_01",
				x = 205,
				y = 115,
				tier = 2,
				requires = "skill_a",
			},
			upg_sa2 = {
				cost = 3,
				title_key = "HERO_ILLIANA_SKILL_A_3_TITLE",
				description_key = "HERO_ILLIANA_SKILL_A_3_DESCRIPTION",
				icon = "hero_illiana_skill_icon_01",
				x = 305,
				y = 115,
				tier = 3,
				requires = "upg_sa1",
			},
			skill_b = {
				cost = 2,
				title_key = "HERO_ILLIANA_SKILL_B_1_TITLE",
				description_key = "HERO_ILLIANA_SKILL_B_1_DESCRIPTION",
				icon = "hero_illiana_skill_icon_02",
				x = 105,
				y = 230,
				tier = 1,
			},
			upg_sb1 = {
				cost = 2,
				title_key = "HERO_ILLIANA_SKILL_B_2_TITLE",
				description_key = "HERO_ILLIANA_SKILL_B_2_DESCRIPTION",
				icon = "hero_illiana_skill_icon_02",
				x = 205,
				y = 230,
				tier = 2,
				requires = "skill_b",
			},
			upg_sb2 = {
				cost = 2,
				title_key = "HERO_ILLIANA_SKILL_B_3_TITLE",
				description_key = "HERO_ILLIANA_SKILL_B_3_DESCRIPTION",
				icon = "hero_illiana_skill_icon_02",
				x = 305,
				y = 230,
				tier = 3,
				requires = "upg_sb1",
			},
			skill_c = {
				cost = 3,
				title_key = "HERO_ILLIANA_SKILL_C_1_TITLE",
				description_key = "HERO_ILLIANA_SKILL_C_1_DESCRIPTION",
				icon = "hero_illiana_skill_icon_03",
				x = 105,
				y = 345,
				tier = 1,
			},
			upg_sc1 = {
				cost = 3,
				title_key = "HERO_ILLIANA_SKILL_C_2_TITLE",
				description_key = "HERO_ILLIANA_SKILL_C_2_DESCRIPTION",
				icon = "hero_illiana_skill_icon_03",
				x = 205,
				y = 345,
				tier = 2,
				requires = "skill_c",
			},
			upg_sc2 = {
				cost = 3,
				title_key = "HERO_ILLIANA_SKILL_C_3_TITLE",
				description_key = "HERO_ILLIANA_SKILL_C_3_DESCRIPTION",
				icon = "hero_illiana_skill_icon_03",
				x = 305,
				y = 345,
				tier = 3,
				requires = "upg_sc1",
			},
			talent_1 = {
				cost = 3,
				title_key = "HERO_ILLIANA_TALENT_1_TITLE",
				description_key = "HERO_ILLIANA_TALENT_1_DESCRIPTION",
				icon = "hero_illiana_skill_icon_04",
				x = 455,
				y = 115,
			},
			talent_2 = {
				cost = 3,
				title_key = "HERO_ILLIANA_TALENT_2_TITLE",
				description_key = "HERO_ILLIANA_TALENT_2_DESCRIPTION",
				icon = "hero_illiana_skill_icon_05",
				x = 565,
				y = 115,
			},
			ulti = {
				cost = 4,
				title_key = "HERO_ILLIANA_ULT_TITLE",
				description_key = "HERO_ILLIANA_ULT_DESCRIPTION",
				icon = "hero_illiana_skill_icon_06",
				x = 675,
				y = 115,
			},
			upg_a = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_RANGE_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_RANGE_INCREASE_DESCRIPTION",
				icon = "icons_passive_range",
				x = 425,
				y = 300,
			},
			upg_b = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_HP_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_health",
				x = 515,
				y = 345,
			},
			upg_c = {
				cost = 2,
				title_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_SKILL_CD_REDUCTION_DESCRIPTION",
				icon = "icons_passive_skill_spawn_time",
				x = 605,
				y = 300,
			},
			upg_d = {
				cost = 1,
				title_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				description_key = "HERO_GENERAL_UPGRADE_BASE_DMG_INCREASE_DESCRIPTION",
				icon = "icons_passive_skill_damage",
				x = 695,
				y = 345,
			},
			upg_e = {
				cost = 2,
				title_key = "HERO_ILLIANA_UPGRADE_DRAGON_DAMAGE",
				description_key = "HERO_ILLIANA_UPGRADE_DRAGON_DAMAGE",
				icon = "icons_passive_skill_damage",
				x = 785,
				y = 300,
			},
		},
	},
	hero_silent = {
		display_key = "HERO_SILENT",
		description_key = "HERO_SILENT_DESC",
		nodes = {
			skill_a = {cost = 1, title_key = "HERO_SILENT_SKILL_A_1_TITLE", description_key = "HERO_SILENT_SKILL_A_1_DESCRIPTION", icon = "hero_silent_skill_icon_01", x = 105, y = 115, tier = 1},
			upg_sa1 = {cost = 2, title_key = "HERO_SILENT_SKILL_A_2_TITLE", description_key = "HERO_SILENT_SKILL_A_2_DESCRIPTION", icon = "hero_silent_skill_icon_01", x = 205, y = 115, tier = 2, requires = "skill_a"},
			upg_sa2 = {cost = 3, title_key = "HERO_SILENT_SKILL_A_3_TITLE", description_key = "HERO_SILENT_SKILL_A_3_DESCRIPTION", icon = "hero_silent_skill_icon_01", x = 305, y = 115, tier = 3, requires = "upg_sa1"},
			skill_b = {cost = 2, title_key = "HERO_SILENT_SKILL_B_1_TITLE", description_key = "HERO_SILENT_SKILL_B_1_DESCRIPTION", icon = "hero_silent_skill_icon_02", x = 105, y = 230, tier = 1},
			upg_sb1 = {cost = 2, title_key = "HERO_SILENT_SKILL_B_2_TITLE", description_key = "HERO_SILENT_SKILL_B_2_DESCRIPTION", icon = "hero_silent_skill_icon_02", x = 205, y = 230, tier = 2, requires = "skill_b"},
			upg_sb2 = {cost = 2, title_key = "HERO_SILENT_SKILL_B_3_TITLE", description_key = "HERO_SILENT_SKILL_B_3_DESCRIPTION", icon = "hero_silent_skill_icon_02", x = 305, y = 230, tier = 3, requires = "upg_sb1"},
			skill_c = {cost = 3, title_key = "HERO_SILENT_SKILL_C_1_TITLE", description_key = "HERO_SILENT_SKILL_C_1_DESCRIPTION", icon = "hero_silent_skill_icon_03", x = 105, y = 345, tier = 1},
			upg_sc1 = {cost = 2, title_key = "HERO_SILENT_SKILL_C_2_TITLE", description_key = "HERO_SILENT_SKILL_C_2_DESCRIPTION", icon = "hero_silent_skill_icon_03", x = 205, y = 345, tier = 2, requires = "skill_c"},
			upg_sc2 = {cost = 3, title_key = "HERO_SILENT_SKILL_C_3_TITLE", description_key = "HERO_SILENT_SKILL_C_3_DESCRIPTION", icon = "hero_silent_skill_icon_03", x = 305, y = 345, tier = 3, requires = "upg_sc1"},
			talent_1 = {cost = 3, title_key = "HERO_SILENT_TALENT_1_TITLE", description_key = "HERO_SILENT_TALENT_1_DESCRIPTION", icon = "hero_silent_skill_icon_04", x = 455, y = 115},
			talent_2 = {cost = 3, title_key = "HERO_SILENT_TALENT_2_TITLE", description_key = "HERO_SILENT_TALENT_2_DESCRIPTION", icon = "hero_silent_skill_icon_05", x = 565, y = 115},
			ulti = {cost = 4, title_key = "HERO_SILENT_ULT_TITLE", description_key = "HERO_SILENT_ULT_DESCRIPTION", icon = "hero_silent_skill_icon_11", x = 675, y = 115},
			upg_a = {cost = 1, title_key = "HERO_SILENT_UPG_A_TITLE", description_key = "HERO_SILENT_UPG_A_DESCRIPTION", icon = "hero_silent_skill_icon_06", x = 425, y = 300},
			upg_b = {cost = 2, title_key = "HERO_SILENT_UPG_B_TITLE", description_key = "HERO_SILENT_UPG_B_DESCRIPTION", icon = "hero_silent_skill_icon_07", x = 515, y = 345},
			upg_c = {cost = 2, title_key = "HERO_SILENT_UPG_C_TITLE", description_key = "HERO_SILENT_UPG_C_DESCRIPTION", icon = "hero_silent_skill_icon_08", x = 605, y = 300},
			upg_d = {cost = 1, title_key = "HERO_SILENT_UPG_D_TITLE", description_key = "HERO_SILENT_UPG_D_DESCRIPTION", icon = "hero_silent_skill_icon_09", x = 695, y = 345},
			upg_e = {cost = 2, title_key = "HERO_SILENT_UPG_E_TITLE", description_key = "HERO_SILENT_UPG_E_DESCRIPTION", icon = "hero_silent_skill_icon_10", x = 785, y = 300}
		}
	},
}
